# Generated by Django 5.0 on 2024-01-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la Empresa')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion de la Empresa')),
            ],
        ),
    ]
