# Generated by Django 5.0 on 2024-01-05 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0002_rename_tarifa_reserva_precio_reserva_hora_fin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='seña',
            new_name='sena',
        ),
    ]
