# Generated by Django 5.0 on 2024-01-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0003_rename_seña_reserva_sena'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='estado_pago',
            new_name='pagado',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='sena',
        ),
        migrations.AddField(
            model_name='reserva',
            name='senado',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
    ]
