# Generated by Django 5.0 on 2024-01-05 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0004_rename_estado_pago_reserva_pagado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='hora_inicio',
        ),
    ]
